In [ ]:
import torch, torch.nn as nn, numpy as np, time

In this segment, we'll get introduced to the 'torch.tensor' object, which in many ways is similar to the NumpPy array.

# NumPy vs Torch:

Arrays (NumPy) and Tensors (Torch) can be created in the same way, resized in similar ways, and most importantly, they have the same brodcasting rules:

In [12]:
n = np.linspace(0, 5, 4)
t = torch.linspace(0, 5, 4)

t

tensor([0.0000, 1.6667, 3.3333, 5.0000])

In [11]:
n = np.arange(48).reshape(3, 4, 4)
t = torch.arange(48).reshape(3, 4, 4)

t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]])

# General Broadcasting Rules:

When operating on two arrays, NumPy compares their shapes element-wise, and works its way from the rightmost dimensions to the leftmost ones. Two dimensions are compatible when 
1. They are equal, or
2. One of them is 1.

In [13]:
a = np.ones((6, 5))
b = np.arange(5).reshape((1, 5))

a, b

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0, 1, 2, 3, 4]]))

In [14]:
a + b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

**Example:** Scale each other the color channels of an Image by a different amount:
- Image (3d array): 256 x 256 x 3
- Scale (1d array): 3

The result is another 3d array 256 x 256 x 3. 

In [15]:
image = torch.randn((256, 256, 3))
scale = torch.tensor([0.5, 1.5, 1])

image * scale

tensor([[[ 0.2139, -1.5012,  1.2484],
         [ 0.0972, -0.1595, -1.5934],
         [ 0.1542,  1.0921,  1.1550],
         ...,
         [ 0.1180, -1.9234,  1.6258],
         [ 0.6996,  2.4288, -0.1129],
         [ 0.2897, -1.1193, -0.4397]],

        [[-0.4412,  0.3644, -1.4884],
         [-0.5261,  1.1316,  0.0172],
         [ 0.4295, -1.6467,  0.2436],
         ...,
         [-0.0990, -1.3096,  0.1734],
         [ 0.1513,  1.6988,  1.1954],
         [-0.5173, -0.3209, -0.5883]],

        [[ 0.4049, -1.4284, -0.6681],
         [ 0.4664, -0.2981, -0.5173],
         [-0.4427,  0.2058, -0.5887],
         ...,
         [-0.1199,  1.0415, -0.9294],
         [-0.3135, -1.0993,  0.4842],
         [ 0.0129, -1.6562, -0.7429]],

        ...,

        [[-0.1566,  1.1129,  0.2646],
         [ 1.0095,  0.1623,  1.9726],
         [ 0.3510, -1.1083, -0.8057],
         ...,
         [ 0.8544, -0.2773,  0.6456],
         [ 0.4258,  1.5245,  0.7352],
         [ 0.7627,  1.6740,  0.7243]],

        [[

# Operations Across Dimensions:

Simple operations can be performed to 1d tensors:

In [16]:
t = torch.tensor([0.5, 1, 3.4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(1.6333), tensor(1.5503), tensor(3.4000), tensor(0.5000))

For a 2d tensor, taking the mean of ech column means doing it across the rows (first dimension)

In [17]:
t = torch.arange(20, dtype = float).reshape(5, 4)
t, torch.mean(t, axis = 0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64))

For higher dimensions, we have the mean across the batch (size = 5):

In [18]:
t = torch.randn(5, 256, 256, 3)
torch.mean(t, axis = 0)

(tensor([[[[ 4.5153e-01, -7.2105e-01,  7.4083e-01],
           [-1.4400e+00, -1.0430e+00,  8.8634e-01],
           [ 1.3145e+00,  1.0517e+00, -3.9852e-02],
           ...,
           [ 1.1182e-02, -2.2777e-01,  1.6968e-01],
           [-7.0938e-01, -7.7350e-02,  1.6236e+00],
           [-8.5134e-01, -1.8333e+00,  8.2358e-01]],
 
          [[-1.5569e+00,  9.3439e-01,  1.6498e+00],
           [-1.8681e+00, -4.0982e-01, -1.2702e+00],
           [-4.8157e-01,  4.3713e-02,  1.6296e-01],
           ...,
           [-1.1161e+00,  1.2993e+00, -1.5376e+00],
           [ 1.0668e-01, -2.8981e-01,  2.0497e+00],
           [-2.4720e+00,  2.7678e+00, -9.1763e-01]],
 
          [[ 8.1555e-01,  6.2704e-02,  1.6683e-01],
           [-9.7313e-01,  1.9951e-01, -1.1328e+00],
           [-4.9862e-01,  1.0268e+00,  6.5819e-01],
           ...,
           [-1.5139e+00,  1.1465e+00, -6.4516e-02],
           [ 1.1843e+00, -3.3462e-01,  4.7373e-01],
           [ 1.0630e+00,  3.6139e-01,  1.8435e-02]],
 
       

And across the color channels:

In [19]:
t, torch.mean(t, axis = -1)

(tensor([[[[ 4.5153e-01, -7.2105e-01,  7.4083e-01],
           [-1.4400e+00, -1.0430e+00,  8.8634e-01],
           [ 1.3145e+00,  1.0517e+00, -3.9852e-02],
           ...,
           [ 1.1182e-02, -2.2777e-01,  1.6968e-01],
           [-7.0938e-01, -7.7350e-02,  1.6236e+00],
           [-8.5134e-01, -1.8333e+00,  8.2358e-01]],
 
          [[-1.5569e+00,  9.3439e-01,  1.6498e+00],
           [-1.8681e+00, -4.0982e-01, -1.2702e+00],
           [-4.8157e-01,  4.3713e-02,  1.6296e-01],
           ...,
           [-1.1161e+00,  1.2993e+00, -1.5376e+00],
           [ 1.0668e-01, -2.8981e-01,  2.0497e+00],
           [-2.4720e+00,  2.7678e+00, -9.1763e-01]],
 
          [[ 8.1555e-01,  6.2704e-02,  1.6683e-01],
           [-9.7313e-01,  1.9951e-01, -1.1328e+00],
           [-4.9862e-01,  1.0268e+00,  6.5819e-01],
           ...,
           [-1.5139e+00,  1.1465e+00, -6.4516e-02],
           [ 1.1843e+00, -3.3462e-01,  4.7373e-01],
           [ 1.0630e+00,  3.6139e-01,  1.8435e-02]],
 
       

We can take only the maximum color channel values and get the corresponding indices. This is done all the time in Linear Segmentation Models (take an image and decide which pixels correspond to a specific object).

In [21]:
values, indices = torch.max(t, axis = -1)
values, indices

(tensor([[[ 0.7408,  0.8863,  1.3145,  ...,  0.1697,  1.6236,  0.8236],
          [ 1.6498, -0.4098,  0.1630,  ...,  1.2993,  2.0497,  2.7678],
          [ 0.8155,  0.1995,  1.0268,  ...,  1.1465,  1.1843,  1.0630],
          ...,
          [ 0.8322,  0.7419,  1.1764,  ..., -0.0512,  0.8816,  1.4345],
          [ 1.4207,  0.1535,  1.8217,  ...,  0.6543, -0.6192,  1.5425],
          [ 2.0298,  0.5612,  0.5776,  ...,  0.7878,  0.3678,  0.3102]],
 
         [[-0.6490,  0.1185,  0.4471,  ...,  0.0397,  1.0360,  2.0236],
          [ 2.1864, -0.1331,  0.6350,  ..., -0.0084,  0.3089,  1.4688],
          [-0.0837,  0.9308,  1.1817,  ...,  0.2492, -0.3989,  0.8879],
          ...,
          [ 1.5245,  0.1089,  0.0806,  ...,  1.6597,  0.9989,  0.5817],
          [ 0.4614,  1.1291, -0.3647,  ...,  2.1667,  1.4213,  0.6986],
          [-0.1286,  0.0627,  1.5878,  ..., -0.3235,  0.5904,  1.4039]],
 
         [[ 0.1506, -0.3226,  1.1403,  ...,  0.3895,  1.6355,  0.4664],
          [ 1.2240,  1.5176,

# Where's the Difference Between the Two?

Pytorch really differs from NumPy in terms of automatically computing gradient operations: $$y=\sum_i x_i^3$$ has a gradient $$\frac{\partial y}{\partial x_i}=3x_i^2$$

In [25]:
x = torch.tensor([[5., 8.], [4., 6.]], requires_grad = True)
y = x.pow(3).sum()

gradient = y.backward()
x.grad

tensor([[ 75., 192.],
        [ 48., 108.]])

In [26]:
3 * x ** 2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)

In general, if one has $y=f(\vec x)$ then PyTorch hcan compute $\partial y/\partial x_i$ for each element of $\vec x.$ In the context of Machine Learning, $\vec x$ contains all the parameters/weights of the neural network and $y$ is the function of the neural network.

# Additional Benefits:

In addition, any sort of large matrix multiplication problem is faster with torch tensors than it is with NumPy arrays.

In [27]:
A = torch.randn((1000, 1000))
B = torch.randn((1000, 1000))

t1 = time.perf_counter()
torch.matmul(A, B)

t2 = time.perf_counter()

t2 - t1

0.059985100000631064